export const darkTheme = {
  backgroundColor: '#1D1D1D',
  headerTextColor: '#B8B8B8',
  linkColor: '#DDDDDD',
  regularTextColor: '#8F8F8F',
  svgIconColor: '#DDDDDD',
  themeSwitchBtn: '#1D1D1D',
  themeSwitchShadow: 'inset 0px 4px 7px 4px rgba(0, 0, 0, 0.8)',
  themeSwitchBackground: '#161616',
  jumpArrowbgColor: '#1D1D1D',
  jumpArrowShadow: '0px 9px 12px rgba(0, 0, 0, 0.26)',
  productBackground: 'transparent',
  productBackgroundActive: '#B8B8B8',
  productText: '#B8B8B8',
  productTextActive: '#1D1D1D',
  svgColorActive: '#1D1D1D',
  svgColor: '#B8B8B8',
  productBorder: '#B8B8B8',
  productBorderActive: 'none',
  prodTitle: '#FFFFFF',
  contImg: '#1D1D1D',
  footerTextColor: '#B8B8B8',
  topFooterTextColor: '#FFFFFF'
};

export const lightTheme = {
  backgroundColor: '#EEEEEE',
  headerTextColor: '#000000',
  regularTextColor: '#333333',
  svgIconColor: '#1D1D1D',
  themeSwitchBtn: '#EEEEEE',
  themeSwitchShadow: 'inset 0px 4px 7px 4px #DDDDDD',
  themeSwitchBackground: '#EEEEEE',
  linkColor: '#1D1D1D',
  jumpArrowbgColor: '#F2F2F2',
  jumpArrowShadow: '0px 9px 12px rgba(0, 0, 0, 0.16)',
  productBackground: 'transparent',
  productBackgroundActive: '#105DCF',
  productTextActive: '#FFFF',
  svgColorActive: '#FFFFFF',
  svgColor: '#1D1D1D',
  productBorder: '#1D1D1D',
  productBorderActive: 'none',
  prodTitle: '#1D1D1D',
  contImg: '#DDDDDD',
  footerTextColor: '#1D1D1D',
  topFooterTextColor: '#1D1D1D'
};
