export const darkTheme = {
  backgroundColor: '#1D1D1D',
  headerTextColor: '#B8B8B8',
  regularTextColor: '#8F8F8F',
  svgIconColor: '#DDDDDD',
  themeSwitchBtn: '#1D1D1D',
  themeSwitchShadow: 'inset 0px 4px 7px 4px rgba(0, 0, 0, 0.8)',
  themeSwitchBackground: '#161616',
  jumpArrowbgColor: '#1D1D1D',
  jumpArrowShadow: '0px 9px 12px rgba(0, 0, 0, 0.26)',
  productBackground: 'transparent',
  productBackgroundActive: '#B8B8B8',
  productText: '#B8B8B8',
  productTextActive: '#1D1D1D',
  svgColorActive: '#1D1D1D',
  svgColor: '#B8B8B8',
  productBorder: '#B8B8B8',
  productBorderActive: 'none',
  prodTitle: '#FFFFFF',
  productDescription: '#ffffff',
  contImg: '#1D1D1D',
  footerTextColor: '#B8B8B8',
  topFooterTextColor: '#FFFFFF',
  teamMemberName: '#B8B8B8',
  teamMemberTitle: '#8F8F8F',
  comingSoon: '#B8B8B8',
  productTitle: '#ffffff',
  teamHeading: '#ffffff',
  teamBody: '#8F8F8F',
  blockTextHead: '#ffffff',
  blockTextBody: '#ffffff'
};

export const lightTheme = {
  backgroundColor: '#EEEEEE',
  headerTextColor: '#000000',
  regularTextColor: '#333333',
  svgIconColor: '#1D1D1D',
  themeSwitchBtn: '#EEEEEE',
  themeSwitchShadow: 'inset 0px 4px 7px 4px #DDDDDD',
  themeSwitchBackground: '#EEEEEE',
  linkColor: '#1D1D1D'
};
