import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'
import styled from 'styled-components'

const Full = styled.div`
  background: #EEEEEE;`

const Home: NextPage = () => {
  return (
    <Full className='full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <NavBar/>
   <Hero/>

    </Full>
  )
}

export default Home
