import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'
import styled from 'styled-components'
import LogoSlide from '../components/LogoSlide'
import DescSec from '../components/DescSec'
import Scroll from '../components/Scroll'
import Rev from '../components/Rev'
import Addr from '../components/Addr'
import Chang from '../components/Chang'
import Mind from '../components/Mind'
import Tabs from '../components/Tabs'

const Full = styled.div`
  background: #EEEEEE;`

const Home: NextPage = () => {
  return (
    <Full className='full'>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Hero/>
   <LogoSlide/>
   <DescSec/>
   <Scroll/>
   <Addr/>
   <Rev/>
   <Chang/>
   <Tabs/>
   <Mind/>


    </Full>
  )
}

export default Home
