import type { NextPage } from 'next'
import Head from 'next/head';
import Layout from '../components/Layout';
import NavBar from '../components/NavBar';
import Hero from '../components/Hero';
import LogoSlide from '../components/LogoSlide';
import DescSec from '../components/DescSec';
import Addr from '../components/Addr';
import Rev from '../components/Rev';
import Chang from '../components/Chang';
import Tabs from '../components/Tabs';
import Footer from '../components/Footer';


const Home: NextPage = () => {
  return (
    <Layout>
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar/>
        
        

        <main >
        <Hero/>
        <LogoSlide/>
        <DescSec/>
        <Addr/>
        <Rev/>
        <Chang/>
        <Tabs/>
        <Footer/>
         

         
          
        </main>

       
      </div>
    </Layout>
  )
}

export default Home
